# Travis CI configuration
---
os: linux
dist: focal
language: python

python:
  - 3.8
  - 3.9

install:
  - pip3 install -r requirements.txt -r requirements-build.txt
  - python setup.py install

script:
  - pytest -v tests

addons:
  apt:
    update: true
    packages:
      - gfortran

notifications:
  email: false

branches:
  only:
    - master
    - dev
